const inputClass = 'w-full rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm outline-none transition shadow-sm focus:border-[#10B981]';

const AddressForm = ({ addressForm, mexicanStates, isSaving, saveError, isEditing, showCancel, onCancel, onChange, onGenderChange, onSubmit }) => (
  <form onSubmit={onSubmit} className="rounded-[28px] border border-slate-200/70 bg-slate-50/50 p-6 shadow-sm sm:p-8">
    <div className="mb-6"><p className="text-[11px] font-bold uppercase tracking-[0.25em] text-emerald-500">{isEditing ? 'Editar dirección' : 'Nueva dirección'}</p><h3 className="mt-2 text-xl font-black text-slate-900">Datos de envío</h3></div>
    <div className="grid grid-cols-2 gap-4 sm:grid-cols-12">
      <Field label="Nombre(s)" name="firstName" value={addressForm.firstName} onChange={onChange} required /><Field label="Apellido(s)" name="lastName" value={addressForm.lastName} onChange={onChange} required />
      <Field label="Teléfono" name="phone" value={addressForm.phone} onChange={onChange} required span="col-span-1 sm:col-span-8" />
      <div className="col-span-1 sm:col-span-4"><label className="mb-1.5 block text-[13px] font-bold text-slate-700">Género</label><div className="flex h-[42px] gap-2 rounded-xl border border-slate-200 bg-slate-50 p-1 shadow-sm"><button type="button" aria-pressed={addressForm.gender === 'H'} onClick={() => onGenderChange('H')} className={`flex-1 rounded-lg border text-xs font-black transition ${addressForm.gender === 'H' ? 'border-emerald-500 bg-emerald-500 text-white shadow-sm' : 'border-slate-200 bg-white text-slate-600 hover:border-emerald-300 hover:bg-emerald-50 hover:text-emerald-700'}`}>H</button><button type="button" aria-pressed={addressForm.gender === 'M'} onClick={() => onGenderChange('M')} className={`flex-1 rounded-lg border text-xs font-black transition ${addressForm.gender === 'M' ? 'border-emerald-500 bg-emerald-500 text-white shadow-sm' : 'border-slate-200 bg-white text-slate-600 hover:border-emerald-300 hover:bg-emerald-50 hover:text-emerald-700'}`}>M</button></div></div>
      <Field label="Calle" name="street" value={addressForm.street} onChange={onChange} required span="col-span-2 sm:col-span-6" /><Field label="No. Ext" name="exteriorNumber" value={addressForm.exteriorNumber} onChange={onChange} required span="col-span-1 sm:col-span-3" /><Field label="No. Int" name="interiorNumber" value={addressForm.interiorNumber} onChange={onChange} span="col-span-1 sm:col-span-3" />
      <Field label="Referencia" name="references" value={addressForm.references} onChange={onChange} textarea span="col-span-2 sm:col-span-12" />
      <Field label="Colonia" name="neighborhood" value={addressForm.neighborhood} onChange={onChange} required /><Field label="C.P." name="postalCode" value={addressForm.postalCode} onChange={onChange} required />
      <Field label="Ciudad" name="city" value={addressForm.city} onChange={onChange} required /><div className="col-span-1 sm:col-span-6"><label className="mb-1.5 block text-[13px] font-bold text-slate-700"><span className="text-rose-500">*</span> Estado</label><select required name="state" value={addressForm.state} onChange={onChange} className={inputClass}><option value="">Selecciona un estado</option>{mexicanStates.map((state) => <option key={state} value={state}>{state}</option>)}</select></div>
    </div>
    <div className="mt-8 flex flex-col-reverse items-center justify-between gap-4 border-t border-slate-200 pt-6 sm:flex-row"><p className="text-xs font-bold text-slate-400"><span className="text-rose-500">*</span> Campos requeridos</p><div className="flex w-full gap-3 sm:w-auto">{showCancel && <button type="button" onClick={onCancel} className="flex-1 rounded-full border border-slate-200 bg-white px-6 py-3.5 text-sm font-bold text-slate-700 transition hover:bg-slate-50 sm:flex-none">Cancelar</button>}<button type="submit" disabled={isSaving} className="flex-1 rounded-full bg-slate-900 px-8 py-3.5 text-sm font-bold text-white transition hover:bg-slate-800 disabled:cursor-not-allowed disabled:opacity-60 sm:flex-none">{isSaving ? 'Guardando...' : isEditing ? 'Guardar cambios' : 'Guardar dirección'}</button></div></div>
    {saveError && <p role="alert" className="mt-4 text-right text-xs font-bold text-rose-500">{saveError}</p>}
  </form>
);

const Field = ({ label, name, value, onChange, required, textarea, span = 'col-span-1 sm:col-span-6' }) => <div className={span}><label className="mb-1.5 block text-[13px] font-bold text-slate-700">{required && <span className="text-rose-500">* </span>}{label}</label>{textarea ? <textarea required={false} name={name} value={value} onChange={onChange} rows="2" className={`${inputClass} resize-none`} /> : <input required={required} name={name} value={value} onChange={onChange} className={inputClass} />}</div>;

export default AddressForm;
