import { useContext, useState } from 'react';
import { AuthContext } from '../../context/AuthContext';
import { useAdvancedProductForm } from '../../hooks/useAdvancedProductForm';

const CATEGORIES = ['procesadores', 'graficas', 'tarjetas madre', 'gabinetes', 'enfriamiento', 'ram', 'almacenamiento', 'fuentes', 'monitores', 'computadora', 'teclados', 'mouses', 'audio'];
const input = 'w-full rounded-2xl border border-slate-200/70 bg-slate-50 px-4 py-3 text-sm font-semibold text-slate-700 outline-none transition duration-200 focus:border-emerald-400 focus:bg-white';
const label = 'mb-1 block pl-1 text-[11px] font-black uppercase tracking-wider text-slate-400';
const Field = ({ name, children }) => <label className="block"><span className={label}>{name}</span>{children}</label>;

const BasicTab = ({ form }) => <div className="space-y-5"><div className="grid gap-4 md:grid-cols-2"><Field name="Nombre"><input required className={input} value={form.formData.name} onChange={(e) => form.setField('name', e.target.value)} /></Field><Field name="Marca"><input required className={input} value={form.formData.brand} onChange={(e) => form.setField('brand', e.target.value)} /></Field><Field name="SKU automático"><input readOnly className={`${input} cursor-not-allowed bg-slate-100 text-slate-500`} value={form.formData.sku} /><span className="mt-1 block text-[10px] font-semibold text-slate-400">Generado automáticamente por FIRSTPC</span></Field><Field name="MPN"><input className={input} placeholder="Ej. 100-100000910WOF" value={form.formData.mpn} onChange={(e) => form.setField('mpn', e.target.value)} /><span className="mt-1 block text-[10px] font-semibold text-slate-400">Código único del fabricante</span></Field><Field name="Categoría"><select className={input} value={form.formData.category} onChange={(e) => form.setField('category', e.target.value)}>{CATEGORIES.map((category) => <option key={category}>{category}</option>)}</select></Field><Field name="Precio MXN"><input required min="0" type="number" className={input} value={form.formData.price} onChange={(e) => form.setField('price', e.target.value)} /></Field><Field name="Stock"><input required min="0" type="number" className={input} value={form.formData.stock} onChange={(e) => form.setField('stock', e.target.value)} /></Field></div><div className="grid gap-4"><Field name="Descripción corta de la marca"><textarea rows="2" className={`${input} resize-none`} value={form.formData.brandAboutText} onChange={(e) => form.setField('brandAboutText', e.target.value)} /></Field><Field name="Título de descripción"><input className={input} value={form.formData.descriptionTitle} onChange={(e) => form.setField('descriptionTitle', e.target.value)} /></Field><Field name="Contenido de la descripción"><textarea rows="7" className={`${input} resize-y`} value={form.formData.descriptionContent} onChange={(e) => form.setField('descriptionContent', e.target.value)} /></Field></div></div>;

const GalleryTab = ({ form }) => <div className="space-y-5"><div><h3 className="text-sm font-black text-slate-800">Fotos del producto</h3><p className="mt-1 text-xs font-medium text-slate-400">Selecciona varias imágenes y usa las flechas para acomodar su orden.</p></div><input ref={form.fileInputRef} type="file" multiple accept="image/*" onChange={form.handleImagesChange} className={`${input} cursor-pointer border-dashed`} /><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{form.existingImages.map((image, index) => <div key={image} className="group relative aspect-square overflow-hidden rounded-2xl border border-slate-200"><img src={image} alt={`Imagen existente ${index + 1}`} className="h-full w-full object-cover" /><div className="absolute inset-x-1 bottom-1 flex justify-between gap-1"><button type="button" onClick={() => form.moveExistingImage(index, -1)} disabled={index === 0} className="h-7 w-7 rounded-full bg-white/90 text-xs font-black text-slate-700 shadow-sm disabled:opacity-40" aria-label="Mover imagen anterior">←</button><button type="button" onClick={() => form.removeExistingImage(image)} className="h-7 w-7 rounded-full bg-rose-500 text-white shadow-sm" aria-label="Eliminar imagen">×</button><button type="button" onClick={() => form.moveExistingImage(index, 1)} disabled={index === form.existingImages.length - 1} className="h-7 w-7 rounded-full bg-white/90 text-xs font-black text-slate-700 shadow-sm disabled:opacity-40" aria-label="Mover imagen siguiente">→</button></div></div>)}{form.previews.map((preview, index) => <div key={preview} className="group relative aspect-square overflow-hidden rounded-2xl border-2 border-emerald-300"><img src={preview} alt={`Vista previa ${index + 1}`} className="h-full w-full object-cover" /><div className="absolute inset-x-1 bottom-1 flex justify-between gap-1"><button type="button" onClick={() => form.moveSelectedFile(index, -1)} disabled={index === 0} className="h-7 w-7 rounded-full bg-white/90 text-xs font-black text-slate-700 shadow-sm disabled:opacity-40" aria-label="Mover vista previa anterior">←</button><span className="h-7 rounded-full bg-emerald-500/90 px-2 text-[10px] font-black leading-7 text-white">Nueva</span><button type="button" onClick={() => form.moveSelectedFile(index, 1)} disabled={index === form.previews.length - 1} className="h-7 w-7 rounded-full bg-white/90 text-xs font-black text-slate-700 shadow-sm disabled:opacity-40" aria-label="Mover vista previa siguiente">→</button></div></div>)}</div></div>;

const SpecsTab = ({ form }) => <div className="space-y-7"><section><div className="mb-3 flex items-center justify-between"><h3 className="text-sm font-black text-slate-800">Especificaciones clave</h3><button type="button" onClick={() => form.setKeySpecRows((rows) => [...rows, { key: '', value: '' }])} className="rounded-full bg-emerald-50 px-4 py-2 text-xs font-black text-emerald-600">+ Añadir característica</button></div>{form.keySpecRows.map((row, index) => <div key={`key-${index}`} className="mb-3 grid grid-cols-[1fr_1fr_auto] gap-2"><input className={input} placeholder="Clave" value={row.key} onChange={(e) => form.updateKeyRow(index, 'key', e.target.value)} /><input className={input} placeholder="Valor" value={row.value} onChange={(e) => form.updateKeyRow(index, 'value', e.target.value)} /><button type="button" onClick={() => form.setKeySpecRows((rows) => rows.filter((_, i) => i !== index))} className="w-11 rounded-2xl bg-rose-50 text-rose-500">×</button></div>)}</section><section className="border-t border-slate-100 pt-6"><div className="mb-3 flex items-center justify-between"><h3 className="text-sm font-black text-slate-800">Especificaciones completas</h3><button type="button" onClick={() => form.setFullSpecRows((rows) => [...rows, { category: '', fields: [{ key: '', value: '' }] }])} className="rounded-full bg-emerald-50 px-4 py-2 text-xs font-black text-emerald-600">+ Añadir categoría</button></div>{form.fullSpecRows.map((group, categoryIndex) => <div key={`category-${categoryIndex}`} className="mb-5 rounded-2xl border border-slate-200 p-4"><div className="mb-3 flex gap-2"><input className={input} placeholder="Categoría técnica" value={group.category} onChange={(e) => form.updateFullRow(categoryIndex, 'category', e.target.value)} /><button type="button" onClick={() => form.setFullSpecRows((rows) => rows.filter((_, i) => i !== categoryIndex))} className="w-11 rounded-2xl bg-rose-50 text-rose-500">×</button></div>{group.fields.map((field, fieldIndex) => <div key={`field-${categoryIndex}-${fieldIndex}`} className="mb-2 grid grid-cols-[1fr_1fr_auto] gap-2"><input className={input} placeholder="Clave" value={field.key} onChange={(e) => form.updateFullField(categoryIndex, fieldIndex, 'key', e.target.value)} /><input className={input} placeholder="Valor" value={field.value} onChange={(e) => form.updateFullField(categoryIndex, fieldIndex, 'value', e.target.value)} /><button type="button" onClick={() => form.updateFullRow(categoryIndex, 'fields', group.fields.filter((_, i) => i !== fieldIndex))} className="w-11 rounded-2xl bg-slate-100 text-slate-500">×</button></div>)}<button type="button" onClick={() => form.updateFullRow(categoryIndex, 'fields', [...group.fields, { key: '', value: '' }])} className="text-xs font-black text-emerald-600">+ Añadir propiedad</button></div>)}</section></div>;

const AddProductModal = ({ isOpen, onClose, product = null, onActionSuccess, onDeleteProduct }) => {
  const { user } = useContext(AuthContext);
  const [activeTab, setActiveTab] = useState('basic');
  const form = useAdvancedProductForm(product, isOpen, onClose, onActionSuccess, user);
  if (!isOpen || user?.role !== 'admin') return null;
  const tabs = [['basic', 'Información básica'], ['gallery', 'Galería'], ['specs', 'Especificaciones']];
  return <div className="fixed inset-0 z-50 flex items-center justify-center overflow-y-auto bg-slate-900/50 p-4 font-['Montserrat'] backdrop-blur-sm"><div className="flex h-[calc(100vh-2rem)] max-h-[900px] w-full max-w-4xl flex-col overflow-hidden rounded-[32px] border border-slate-100 bg-white shadow-[0_25px_80px_rgba(15,23,42,0.2)]"><header className="flex shrink-0 items-center justify-between border-b border-slate-100 px-6 py-5 md:px-8"><div><p className="text-xs font-black uppercase tracking-[.2em] text-emerald-500">Administración de productos</p><h2 className="mt-1 text-xl font-black text-slate-900">{product ? 'Editar componente' : 'Agregar nuevo componente'}</h2></div><button type="button" onClick={form.handleClose} disabled={form.loading} className="h-10 w-10 rounded-full bg-slate-100 text-xl text-slate-500">×</button></header><nav className="flex shrink-0 gap-2 overflow-x-auto border-b border-slate-100 px-6 pt-4 md:px-8">{tabs.map(([key, name]) => <button key={key} type="button" onClick={() => setActiveTab(key)} className={`whitespace-nowrap border-b-2 px-3 pb-3 text-xs font-black ${activeTab === key ? 'border-emerald-500 text-emerald-600' : 'border-transparent text-slate-400'}`}>{name}</button>)}</nav><form onSubmit={form.handleSubmit} className="min-h-0 flex-1 overflow-y-auto px-6 py-6 md:px-8">{activeTab === 'basic' && <BasicTab form={form} />}{activeTab === 'gallery' && <GalleryTab form={form} />}{activeTab === 'specs' && <SpecsTab form={form} />}</form><footer className="shrink-0 border-t border-slate-100 px-6 py-5 md:px-8">{form.errorMessage && <p className="mb-3 rounded-2xl bg-rose-50 px-4 py-3 text-xs font-bold text-rose-600">{form.errorMessage}</p>}<div className="flex flex-wrap gap-3"><button type="button" onClick={form.handleClose} disabled={form.loading} className="rounded-full bg-slate-100 px-6 py-3 text-sm font-black text-slate-600">Cancelar</button>{product && <button type="button" onClick={() => onDeleteProduct?.(product)} disabled={form.loading} className="rounded-full border border-rose-200 px-6 py-3 text-sm font-black text-rose-500 transition duration-200 hover:bg-rose-50">Eliminar producto</button>}<button type="button" onClick={form.handleSubmit} disabled={form.loading} className="ml-auto rounded-full bg-[#10B981] px-6 py-3 text-sm font-black text-white shadow-lg transition duration-200 hover:bg-emerald-600 disabled:opacity-60">{form.loading ? 'Guardando producto y subiendo imágenes...' : product ? 'Actualizar producto' : 'Guardar producto'}</button></div></footer></div></div>;
};

export default AddProductModal;
