import { AlertTriangle, ChevronDown, RefreshCw, Search, SlidersHorizontal } from "lucide-react";
import Navbar from "../components/Navbar";
import Footer from "../components/Home/Footer";
import InventoryTable from "../components/AdminInventory/InventoryTable";
import useAdminInventory from "../components/AdminInventory/useAdminInventory";

const AdminInventory = () => {
  const { search, setSearch, category, setCategory, criticalOnly, setCriticalOnly, loading, error, filteredProducts, counts, modalProduct, setModalProduct, savingId, saveProduct, CATEGORIES, getImage, getStock, money, stockState } = useAdminInventory();

  return <section className="bg-slate-50 px-4 pt-36 font-['Montserrat'] text-slate-800 md:px-8 md:pt-40 lg:px-12"><Navbar /><div className="mx-auto max-w-[1500px]">
    <header className="mb-8 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><h1 className="text-3xl font-black tracking-tight text-slate-900 md:text-4xl">Control de <span className="text-emerald-600">Inventario</span></h1><p className="mt-1 text-xs text-slate-500">Supervisa las existencias, edita precios y gestiona el stock en tiempo real.</p></div></header>
    <div className="mb-6 grid grid-cols-2 gap-3 lg:grid-cols-4"><div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><p className="text-[10px] font-bold uppercase tracking-wider text-slate-500">Total Catálogo</p><p className="mt-2 text-2xl font-black text-slate-900">{counts.total}</p></div><div className="rounded-2xl border border-amber-200 bg-amber-50/60 p-4 shadow-sm"><p className="text-[10px] font-bold uppercase tracking-wider text-amber-700">Stock Crítico (≤4)</p><p className="mt-2 text-2xl font-black text-amber-800">{counts.low}</p></div><div className="rounded-2xl border border-red-200 bg-red-50/60 p-4 shadow-sm"><p className="text-[10px] font-bold uppercase tracking-wider text-red-700">Agotados (0)</p><p className="mt-2 text-2xl font-black text-red-800">{counts.out}</p></div><div className="rounded-2xl border border-emerald-200 bg-emerald-50/60 p-4 shadow-sm"><p className="text-[10px] font-bold uppercase tracking-wider text-emerald-700">Existencias</p><p className="mt-2 text-2xl font-black text-emerald-800">{counts.available}</p></div></div>
    <div className="mb-5 rounded-2xl border border-slate-200 bg-white p-3 shadow-sm"><div className="flex flex-col gap-3 lg:flex-row"><label className="relative flex-1"><Search size={17} className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Buscar por nombre, SKU o número de parte MPN..." className="w-full rounded-xl border border-slate-200 bg-slate-50 py-3 pl-11 pr-4 text-xs font-semibold text-slate-800 outline-none transition placeholder:text-slate-400 focus:border-emerald-500 focus:bg-white focus:ring-1 focus:ring-emerald-500" /></label><div className="relative"><SlidersHorizontal size={15} className="pointer-events-none absolute left-4 top-1/2 -translate-y-1/2 text-slate-400" /><select value={category} onChange={(event) => setCategory(event.target.value)} className="w-full appearance-none rounded-xl border border-slate-200 bg-slate-50 py-3 pl-10 pr-10 text-xs font-bold text-slate-700 outline-none focus:border-emerald-500 focus:bg-white lg:w-60">{CATEGORIES.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><ChevronDown size={15} className="pointer-events-none absolute right-4 top-1/2 -translate-y-1/2 text-slate-400" /></div><button type="button" onClick={() => setCriticalOnly((value) => !value)} className={`inline-flex items-center justify-center gap-2 rounded-xl px-4 py-3 text-xs font-black uppercase tracking-wider transition ${criticalOnly ? "bg-red-600 text-white shadow-md shadow-red-500/20" : "border border-red-200 bg-red-50 text-red-700 hover:bg-red-100"}`}><AlertTriangle size={15} /> Solo Alertas</button></div></div>
    {error && <div className="mb-5 flex items-center justify-between rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-xs text-red-700"><span>{error}</span><button type="button" onClick={() => window.location.reload()} aria-label="Reintentar"><RefreshCw size={15} /></button></div>}
    <InventoryTable products={filteredProducts} loading={loading} getImage={getImage} getStock={getStock} money={money} stockState={stockState} modalProduct={modalProduct} setModalProduct={setModalProduct} savingId={savingId} saveProduct={saveProduct} />
  </div><div className="mt-24"><Footer /></div></section>;
};

export default AdminInventory;
